#!/usr/bin/env bash

echo "Generating Xcode Project..."

if [ ! -f App.xcconfig ]; then
    touch App.xcconfig

    YOGA_LIB_PATH=$(find . -wholename '*/Sources/Yoga/darwin*' | head -n 1);
    echo "MACOSX_DEPLOYMENT_TARGET = 10.13" >> App.xcconfig
    echo "OTHER_LDFLAGS = -L$YOGA_LIB_PATH -lc++" >> App.xcconfig
fi

swift package generate-xcodeproj --xcconfig-overrides App.xcconfig
open App.xcodeproj
